#!/usr/bin/env bash
cargo build --release

/bin/cp ./initdb.sql /tmp/initdb.sql
/bin/cp ./tokei_rs.service /etc/systemd/system/tokei_rs.service

sudo -u tokei_rs psql -f /tmp/initdb.sql

systemctl stop tokei_rs.service
/bin/cp ./target/release/tokei_rs /opt/tokei_rs
systemctl daemon-reload
systemctl start tokei_rs.service

crontab ./cron
